config/routes.rb
Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server => '/info/resque', as: 'resque'

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git_bin_path,
    project_root: Gitlab.config.git_base_path,
    upload_pack:  Gitlab.config.git_upload_pack,
    receive_pack: Gitlab.config.git_receive_pack
  }), at: '/:path', constraints: { path: /[\w-]+\.git/ }

  #
  # Help
  #
  get 'help'              => 'help#index'
  get 'help/permissions'  => 'help#permissions'
  get 'help/workflow'     => 'help#workflow'
  get 'help/api'          => 'help#api'
  get 'help/web_hooks'    => 'help#web_hooks'
  get 'help/system_hooks' => 'help#system_hooks'
  get 'help/markdown'     => 'help#markdown'
  get 'help/ssh'          => 'help#ssh'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, constraints: { id: /[^\/]+/ } do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, only: [:edit, :update, :destroy]
    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end
    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  get "profile/account"             => "profile#account"
  get "profile/history"             => "profile#history"
  put "profile/password"            => "profile#password_update"
  get "profile/token"               => "profile#token"
  put "profile/reset_private_token" => "profile#reset_private_token"
  get "profile"                     => "profile#show"
  get "profile/design"              => "profile#design"
  put "profile/update"              => "profile#update"

  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard"                => "dashboard#index"
  get "dashboard/issues"         => "dashboard#issues"
  get "dashboard/merge_requests" => "dashboard#merge_requests"

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[^\/]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [], path: "/" do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :raw
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /.+/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/}
    match "/compare/:from...:to" => "compare#show", as: "compare", constraints: {from: /.+/, to: /.+/}

    resources :team, controller: 'team_members', only: [:index]
    resources :team_members
    resources :milestones
    resources :labels, only: [:index]
    resources :issues do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#index"
end

app/models/note.rb
require 'carrierwave/orm/activerecord'
require 'file_size_validator'

class Note < ActiveRecord::Base
  mount_uploader  :attachment, AttachmentUploader
  attr_accessible :note, :noteable, :noteable_id, :noteable_type, :project_id,
                  :attachment, :line_code

  belongs_to :project
  belongs_to :noteable, polymorphic: true
  belongs_to :author, class_name: "User"

  delegate :name, to: :project, prefix: true
  delegate :name, :email, to: :author, prefix: true

  attr_accessor :notify
  attr_accessor :notify_author

  validates_presence_of :project

  validates :note, presence: true, length: { within: 0..5000 }
  validates :attachment, file_size: { maximum: 10.megabytes.to_i }

  scope :common, where(noteable_id: nil)
  scope :today, where("created_at >= :date", date: Date.today)
  scope :last_week, where("created_at  >= :date", date: (Date.today - 7.days))
  scope :since, lambda { |day| where("created_at  >= :date", date: (day)) }
  scope :fresh, order("created_at ASC, id ASC")
  scope :inc_author_project, includes(:project, :author)
  scope :inc_author, includes(:author)

  def self.create_status_change_note(noteable, author, status)
    create({
      noteable: noteable,
      project: noteable.project,
      author: author,
      note: "_Status changed to #{status}_"
    }, without_protection: true)
  end

  def notify
    @notify ||= false
  end

  def notify_author
    @notify_author ||= false
  end

  def target
    if noteable_type == "Commit"
      project.commit(noteable_id)
    else
      noteable
    end
  # Temp fix to prevent app crash
  # if note commit id doesnt exist
  rescue
    nil
  end

  # Check if we can notify commit author
  # with email about our comment
  #
  # If commit author email exist in project
  # and commit author is not passed user we can
  # send email to him
  #
  # params:
  #   user - current user
  #
  # return:
  #   Boolean
  #
  def notify_only_author?(user)
    commit? && commit_author &&
      commit_author.email != user.email
  end

  def commit?
    noteable_type == "Commit"
  end

  def commit_author
    @commit_author ||=
      project.users.find_by_email(target.author_email) ||
      project.users.find_by_name(target.author_name)
  rescue
    nil
  end

  # Returns true if this is an upvote note,
  # otherwise false is returned
  def upvote?
    note.start_with?('+1') || note.start_with?(':+1:')
  end

  # Returns true if this is a downvote note,
  # otherwise false is returned
  def downvote?
    note.start_with?('-1') || note.start_with?(':-1:')
  end
end

# == Schema Information
#
# Table name: notes
#
#  id            :integer         not null, primary key
#  note          :text
#  noteable_id   :string(255)
#  noteable_type :string(255)
#  author_id     :integer
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#  project_id    :integer
#  attachment    :string(255)
#  line_code     :string(255)
#

app/controllers/notes_controller.rb
class NotesController < ProjectResourceController
  # Authorize
  before_filter :authorize_read_note!
  before_filter :authorize_write_note!, only: [:create]

  respond_to :js

  def index
    notes
    respond_with(@notes)
  end

  def create
    @note = Notes::CreateContext.new(project, current_user, params).execute

    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def destroy
    @note = @project.notes.find(params[:id])
    return access_denied! unless can?(current_user, :admin_note, @note)
    @note.destroy

    respond_to do |format|
      format.js { render nothing: true }
    end
  end

  def preview
    render text: view_context.markdown(params[:note])
  end

  protected

  def notes
    @notes = Notes::LoadContext.new(project, current_user, params).execute
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def loading_more_notes?
    params[:loading_more].present?
  end

  def loading_new_notes?
    params[:loading_new].present?
  end

  def note_vote_class(note)
    if note.upvote?
      "vote upvote"
    elsif note.downvote?
      "vote downvote"
    end
  end
end

app/views/notes/_common_form.html.haml
.note-form-holder
  = form_for [@project, @note], remote: "true", multipart: true do |f|
    %h3.page_title Leave a comment
    -if @note.errors.any?
      .alert-message.block-message.error
        - @note.errors.full_messages.each do |msg|
          %div= msg

    = f.hidden_field :noteable_id
    = f.hidden_field :noteable_type
    = f.text_area :note, size: 255, class: 'note-text'
    #preview-note.preview_note.hide
    .hint
      .right Comments are parsed with #{link_to "GitLab Flavored Markdown", help_markdown_path, target: '_blank'}.
      .clearfix

    .row.note_advanced_opts
      .span3
        = f.submit 'Add Comment', class: "btn success submit_note grouped", id: "submit_note"
        = link_to 'Preview', preview_project_notes_path(@project), class: 'btn grouped', id: 'preview-link'
      .span4.notify_opts
        %h6.left Notify via email:
        = label_tag :notify do
          = check_box_tag :notify, 1, @note.noteable_type != "Commit"
          %span Project team

        - if @note.notify_only_author?(current_user)
          = label_tag :notify_author do
            = check_box_tag :notify_author, 1 , @note.noteable_type == "Commit"
            %span Commit author
      .span5.attachments
        %h6.left Attachment:
        %span.file_name File name...

        .input.input_file
          %a.file_upload.btn.small Upload File
          = f.file_field :attachment, class: "input-file"
        %span.hint Any file less than 10 MB

:javascript
  $(function(){
    var names = #{@project.users.pluck(:name)}, emoji = ['+1', '-1'];
    var emoji = $.map(emoji, function(value, i) {return {key:value + ':', name:value}});
    $('#note_note, .per_line_form .line-note-text').
      atWho('@', { data: names }).
      atWho(':', {
        data: emoji,
        tpl: "<li data-value='${key}'>${name} #{escape_javascript image_tag('emoji/${name}.png', :size => '20x20')}</li>"
      });
  });

app/views/notes/_create_common_note.js.haml
- if note.valid?
  :plain
    $(".note-form-holder .error").remove();
    $('.note-form-holder textarea').val("");
    $('.note-form-holder #preview-link').text('Preview');
    $('.note-form-holder #preview-note').hide();
    $('.note-form-holder').show();
    NoteList.appendNewNote(#{note.id}, "#{escape_javascript(render "notes/note", note: note)}");

- else
  :plain
    $(".note-form-holder").replaceWith("#{escape_javascript(render 'form')}");

app/views/notes/_create_per_line_note.js.haml
- if note.valid?
  :plain
    // hide and reset the form
    $(".per_line_form").hide();
    $('.line-note-form-holder textarea').val("");

    // find the reply button for this line
    // (might not be there if this is the first note)
    var trRpl = $("a.line_note_reply_link[data-line-code='#{note.line_code}']").closest("tr");
    if (trRpl.size() == 0) {
      // find the commented line ...
      var trEl = $(".#{note.line_code}").parent();
      // ... and insert the note and the reply button after it
      trEl.after("#{escape_javascript(render "notes/per_line_reply_button", line_code: note.line_code)}");
      trEl.after("#{escape_javascript(render "notes/per_line_note", note: note)}");
    } else {
      // instert new note before reply button
      trRpl.before("#{escape_javascript(render "notes/per_line_note", note: note)}");
    }

app/views/notes/_note.html.haml
%li{id: dom_id(note), class: "note #{note_vote_class(note)}"}
  = image_tag gravatar_icon(note.author.email), class: "avatar s32"
  %div.note-author
    %strong= note.author_name
    = link_to "##{dom_id(note)}", name: dom_id(note) do
      %cite.cgray
        = time_ago_in_words(note.updated_at)
        ago
    - if note.upvote?
      %span.label.label-success
        %i.icon-thumbs-up
        \+1
    - if note.downvote?
      %span.label.label-error
        %i.icon-thumbs-down
        \-1
    - if(note.author_id == current_user.id) || can?(current_user, :admin_note, @project)
      = link_to [@project, note], confirm: 'Are you sure?', method: :delete, remote: true, class: "cred delete-note btn very_small" do
        %i.icon-trash
        Remove

  %div.note-title
    = preserve do
      = markdown(note.note)
    - if note.attachment.url
      .right
        %div.file
          = link_to note.attachment_identifier, note.attachment.url, target: "_blank"
  .clear

app/views/notes/_notes.html.haml
- @notes.each do |note|
  - next unless note.author
  = render "note", note: note

app/views/notes/_notes_with_form.html.haml
%ul#notes-list
%ul#new-notes-list
.notes-status

- if can? current_user, :write_note, @project
  = render "notes/common_form"

:javascript
  $(function(){
    NoteList.init("#{tid}", "#{tt}", "#{project_notes_path(@project)}");
  });

app/views/notes/_per_line_form.html.haml
%table{style: "display:none;"}
  %tr.per_line_form
    %td{colspan: 3 }
      .line-note-form-holder
        = form_for [@project, @note], remote: "true", multipart: true do |f|
          %h3.page_title Leave a note
          %div.span10
            -if @note.errors.any?
              .alert-message.block-message.error
                - @note.errors.full_messages.each do |msg|
                  %div= msg

            = f.hidden_field :noteable_id
            = f.hidden_field :noteable_type
            = f.hidden_field :line_code
            = f.text_area :note,  size: 255, class: 'line-note-text'
            .note_actions
              .buttons
                = f.submit 'Add note', class: "btn save-btn submit_note submit_inline_note", id: "submit_note"
                = link_to "Cancel", "#", class: "btn hide-button"
              .options
                %h6.left Notify via email:
                .labels
                  = label_tag :notify do
                    = check_box_tag :notify, 1, @note.noteable_type != "Commit"
                    %span Project team

                  - if @note.notify_only_author?(current_user)
                    = label_tag :notify_author do
                      = check_box_tag :notify_author, 1 , @note.noteable_type == "Commit"
                      %span Commit author

:javascript
  $(function(){
    $(".per_line_form .hide-button").bind("click", function(){
      $('.per_line_form').hide();
      return false;
    });
  });

app/views/notes/_per_line_note.html.haml
%tr.line_notes_row
  %td{colspan: 3}
    %ul
      = render "notes/note", note: note

app/views/notes/_per_line_note_link.html.haml
= link_to "", "#", class: "line_note_link", data: { line_code: line_code }, title: "Add note for this line"

app/views/notes/_per_line_notes_with_reply.html.haml
- notes.each do |note|
  = render "notes/per_line_note", note: note
= render "notes/per_line_reply_button", line_code: notes.first.line_code

app/views/notes/_per_line_reply_button.html.haml
%tr.line_notes_row.reply
  %td{colspan: 3}
    %i.icon-comment
    = link_to "Reply", "#", class: "line_note_reply_link", data: { line_code: line_code }, title: "Add note for this line"

app/views/notes/_reversed_notes_with_form.html.haml
- if can? current_user, :write_note, @project
  = render "notes/common_form"

%ul.reversed#new-notes-list
%ul.reversed#notes-list
.notes-status

:javascript
  $(function(){
    NoteList.init("#{tid}", "#{tt}", "#{project_notes_path(@project)}");
  });

app/views/notes/create.js.haml
- if @note.line_code
  = render "create_per_line_note", note: @note
- else
  = render "create_common_note", note: @note

-# Enable submit button
:plain
  $("#submit_note").removeAttr("disabled");

app/views/notes/index.js.haml
- unless @notes.blank?
  - if loading_more_notes?
    :plain
      NoteList.appendMoreNotes(#{@notes.last.id}, "#{escape_javascript(render 'notes/notes')}");

  - elsif loading_new_notes?
    :plain
      NoteList.replaceNewNotes("#{escape_javascript(render 'notes/notes')}");

  - else
    :plain
      NoteList.setContent(#{@notes.first.id}, #{@notes.last.id}, "#{escape_javascript(render 'notes/notes')}");

- else
  - if loading_more_notes?
    :plain
      NoteList.finishedLoadingMore();