config/routes.rb
Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server => '/info/resque', as: 'resque'

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git_bin_path,
    project_root: Gitlab.config.git_base_path,
    upload_pack:  Gitlab.config.git_upload_pack,
    receive_pack: Gitlab.config.git_receive_pack
  }), at: '/:path', constraints: { path: /[\w-]+\.git/ }

  #
  # Help
  #
  get 'help'              => 'help#index'
  get 'help/permissions'  => 'help#permissions'
  get 'help/workflow'     => 'help#workflow'
  get 'help/api'          => 'help#api'
  get 'help/web_hooks'    => 'help#web_hooks'
  get 'help/system_hooks' => 'help#system_hooks'
  get 'help/markdown'     => 'help#markdown'
  get 'help/ssh'          => 'help#ssh'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, constraints: { id: /[^\/]+/ } do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, only: [:edit, :update, :destroy]
    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end
    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  get "profile/account"             => "profile#account"
  get "profile/history"             => "profile#history"
  put "profile/password"            => "profile#password_update"
  get "profile/token"               => "profile#token"
  put "profile/reset_private_token" => "profile#reset_private_token"
  get "profile"                     => "profile#show"
  get "profile/design"              => "profile#design"
  put "profile/update"              => "profile#update"

  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard"                => "dashboard#index"
  get "dashboard/issues"         => "dashboard#issues"
  get "dashboard/merge_requests" => "dashboard#merge_requests"

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[^\/]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [], path: "/" do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :raw
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /.+/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/}
    match "/compare/:from...:to" => "compare#show", as: "compare", constraints: {from: /.+/, to: /.+/}

    resources :team, controller: 'team_members', only: [:index]
    resources :team_members
    resources :milestones
    resources :labels, only: [:index]
    resources :issues do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#index"
end

app/controllers/repositories_controller.rb
class RepositoriesController < ProjectResourceController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @activities = @project.commits_with_refs(20)
  end

  def branches
    @branches = @project.branches
  end

  def tags
    @tags = @project.tags
  end

  def archive
    unless can?(current_user, :download_code, @project)
      render_404 and return 
    end


    file_path = @project.archive_repo(params[:ref])

    if file_path
      # Send file to user
      send_file file_path
    else
      render_404
    end
  end
end

app/views/repositories/_branch.html.haml
- commit = Commit.new(branch.commit)
- commit = CommitDecorator.decorate(commit)
%tr
  %td
    = link_to project_commits_path(@project, branch.name) do
      %strong= truncate(branch.name, length: 60)
      - if branch.name == @project.root_ref
        %span.label default
  %td
    = link_to project_commit_path(@project, commit) do
      %code= commit.short_id

    = image_tag gravatar_icon(commit.author_email), class: "", width: 16
    = gfm escape_once(truncate(commit.title, length: 40))
    %span.update-author.right
      = time_ago_in_words(commit.committed_date)
      ago
  %td
    - if can? current_user, :download_code, @project
      = link_to "Download", archive_project_repository_path(@project, ref: branch.name), class: "visible_link download_repo_link"

app/views/repositories/_branches_head.html.haml
= render "commits/head"
%ul.nav.nav-pills
  = nav_link(path: 'repositories#show') do
    = link_to 'Recent', project_repository_path(@project)
  = nav_link(path: 'protected_branches#index') do
    = link_to 'Protected', project_protected_branches_path(@project)
  = nav_link(path: 'repositories#branches') do
    = link_to 'All', branches_project_repository_path(@project)

app/views/repositories/_feed.html.haml
- commit = update
- commit = CommitDecorator.new(commit)
%tr
  %td
    = link_to project_commits_path(@project, commit.head.name) do
      %strong
        = commit.head.name
      - if commit.head.name == @project.root_ref
        %span.label default

  %td
    %div
      = link_to project_commits_path(@project, commit.id) do
        %code= commit.short_id
      = image_tag gravatar_icon(commit.author_email), class: "", width: 16
      = gfm escape_once(truncate(commit.title, length: 40))
  %td
    %span.right.cgray
      = time_ago_in_words(commit.committed_date)
      ago

app/views/repositories/_head.html.haml
= render "projects/project_head"

app/views/repositories/branches.html.haml
= render "repositories/branches_head"
- unless @branches.empty?
  %table
    %thead
      %tr
        %th Name
        %th Last commit
        %th

    %tbody
      - @branches.each do |branch|
        = render "repositories/branch", branch: branch

app/views/repositories/show.html.haml
= render "branches_head"

%table
  %thead
    %tr
      %th Name
      %th Last commit
      %th
  - @activities.each do |update|
    = render "repositories/branch", branch: update.head

app/views/repositories/tags.html.haml
= render "commits/head"
- unless @tags.empty?
  %table
    %thead
      %tr
        %th Name
        %th Last commit
        %th Updated at
        %th
    - @tags.each do |tag|
      - commit = Commit.new(tag.commit)
      - commit = CommitDecorator.decorate(commit)
      %tr
        %td
          %strong= link_to tag.name, project_commits_path(@project, tag.name), class: ""
        %td
          = link_to project_commit_path(@project, commit.id) do
            %code= commit.short_id
          = image_tag gravatar_icon(commit.author_email), class: "", width: 16
          = gfm escape_once(truncate(commit.title, length: 40))
        %td
          %span.update-author.right
            = time_ago_in_words(commit.committed_date)
            ago
            &nbsp;
        %td
          - if can? current_user, :download_code, @project
            = link_to "Download", archive_project_repository_path(@project, ref: tag.name), class: "visible_link download_repo_link"

- else
  %h3 No tags