config/routes.rb
Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server => '/info/resque', as: 'resque'

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git_bin_path,
    project_root: Gitlab.config.git_base_path,
    upload_pack:  Gitlab.config.git_upload_pack,
    receive_pack: Gitlab.config.git_receive_pack
  }), at: '/:path', constraints: { path: /[\w-]+\.git/ }

  #
  # Help
  #
  get 'help'              => 'help#index'
  get 'help/permissions'  => 'help#permissions'
  get 'help/workflow'     => 'help#workflow'
  get 'help/api'          => 'help#api'
  get 'help/web_hooks'    => 'help#web_hooks'
  get 'help/system_hooks' => 'help#system_hooks'
  get 'help/markdown'     => 'help#markdown'
  get 'help/ssh'          => 'help#ssh'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, constraints: { id: /[^\/]+/ } do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, only: [:edit, :update, :destroy]
    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end
    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  get "profile/account"             => "profile#account"
  get "profile/history"             => "profile#history"
  put "profile/password"            => "profile#password_update"
  get "profile/token"               => "profile#token"
  put "profile/reset_private_token" => "profile#reset_private_token"
  get "profile"                     => "profile#show"
  get "profile/design"              => "profile#design"
  put "profile/update"              => "profile#update"

  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard"                => "dashboard#index"
  get "dashboard/issues"         => "dashboard#issues"
  get "dashboard/merge_requests" => "dashboard#merge_requests"

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[^\/]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [], path: "/" do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :raw
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /.+/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/}
    match "/compare/:from...:to" => "compare#show", as: "compare", constraints: {from: /.+/, to: /.+/}

    resources :team, controller: 'team_members', only: [:index]
    resources :team_members
    resources :milestones
    resources :labels, only: [:index]
    resources :issues do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#index"
end

app/models/project.rb
require "grit"

class Project < ActiveRecord::Base
  include Repository
  include PushObserver
  include Authority
  include Team

  attr_accessible :name, :path, :description, :code, :default_branch, :issues_enabled,
                  :wall_enabled, :merge_requests_enabled, :wiki_enabled
  attr_accessor :error_code

  # Relations
  belongs_to :owner, class_name: "User"
  has_many :users,          through: :users_projects
  has_many :events,         dependent: :destroy
  has_many :merge_requests, dependent: :destroy
  has_many :issues,         dependent: :destroy, order: "closed, created_at DESC"
  has_many :milestones,     dependent: :destroy
  has_many :users_projects, dependent: :destroy
  has_many :notes,          dependent: :destroy
  has_many :snippets,       dependent: :destroy
  has_many :deploy_keys,    dependent: :destroy, foreign_key: "project_id", class_name: "Key"
  has_many :hooks,          dependent: :destroy, class_name: "ProjectHook"
  has_many :wikis,          dependent: :destroy
  has_many :protected_branches, dependent: :destroy

  # Scopes
  scope :public_only, where(private_flag: false)
  scope :without_user, lambda { |user|  where("id not in (:ids)", ids: user.projects.map(&:id) ) }

  def self.active
    joins(:issues, :notes, :merge_requests).order("issues.created_at, notes.created_at, merge_requests.created_at DESC")
  end

  def self.search query
    where("name like :query or code like :query or path like :query", query: "%#{query}%")
  end

  def self.create_by_user(params, user)
    project = Project.new params

    Project.transaction do
      project.owner = user
      project.save!

      # Add user as project master
      project.users_projects.create!(project_access: UsersProject::MASTER, user: user)

      # when project saved no team member exist so
      # project repository should be updated after first user add
      project.update_repository
    end

    project
  rescue Gitlab::Gitolite::AccessDenied => ex
    project.error_code = :gitolite
    project
  rescue => ex
    project.error_code = :db
    project.errors.add(:base, "Can't save project. Please try again later")
    project
  end

  def git_error?
    error_code == :gitolite
  end

  def saved?
    id && valid?
  end

  # Validations
  validates :owner, presence: true
  validates :description, length: { within: 0..2000 }
  validates :name, uniqueness: true, presence: true, length: { within: 0..255 }
  validates :path, uniqueness: true, presence: true, length: { within: 0..255 },
            format: { with: /\A[a-zA-Z][a-zA-Z0-9_\-\.]*\z/,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }
  validates :code, presence: true, uniqueness: true, length: { within: 1..255 },
            format: { with: /\A[a-zA-Z][a-zA-Z0-9_\-\.]*\z/,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }
  validates :issues_enabled, :wall_enabled, :merge_requests_enabled,
            :wiki_enabled, inclusion: { in: [true, false] }
  validate :check_limit, :repo_name

  def check_limit
    unless owner.can_create_project?
      errors[:base] << ("Your own projects limit is #{owner.projects_limit}! Please contact administrator to increase it")
    end
  rescue
    errors[:base] << ("Can't check your ability to create project")
  end

  def repo_name
    if path == "gitolite-admin"
      errors.add(:path, " like 'gitolite-admin' is not allowed")
    end
  end

  def self.access_options
    UsersProject.access_roles
  end

  def to_param
    code
  end

  def web_url
    [Gitlab.config.url, code].join("/")
  end

  def common_notes
    notes.where(noteable_type: ["", nil]).inc_author_project
  end

  def build_commit_note(commit)
    notes.new(noteable_id: commit.id, noteable_type: "Commit")
  end

  def commit_notes(commit)
    notes.where(noteable_id: commit.id, noteable_type: "Commit", line_code: nil)
  end

  def commit_line_notes(commit)
    notes.where(noteable_id: commit.id, noteable_type: "Commit").where("line_code is not null")
  end

  def public?
    !private_flag
  end

  def private?
    private_flag
  end

  def last_activity
    events.order("created_at ASC").last
  end

  def last_activity_date
    if events.last
      events.last.created_at
    else
      updated_at
    end
  end

  def wiki_notes
    Note.where(noteable_id: wikis.pluck(:id), noteable_type: 'Wiki', project_id: self.id)
  end

  def project_id
    self.id
  end
end

# == Schema Information
#
# Table name: projects
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  path                   :string(255)
#  description            :text
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  private_flag           :boolean         default(TRUE), not null
#  code                   :string(255)
#  owner_id               :integer
#  default_branch         :string(255)
#  issues_enabled         :boolean         default(TRUE), not null
#  wall_enabled           :boolean         default(TRUE), not null
#  merge_requests_enabled :boolean         default(TRUE), not null
#  wiki_enabled           :boolean         default(TRUE), not null
#

app/controllers/admin/team_members_controller.rb
class Admin::TeamMembersController < AdminController
  def edit
    @admin_team_member = UsersProject.find(params[:id])
  end

  def update
    @admin_team_member = UsersProject.find(params[:id])

    if @admin_team_member.update_attributes(params[:team_member])
      redirect_to [:admin, @admin_team_member.project],  notice: 'Project Access was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @admin_team_member = UsersProject.find(params[:id])
    @admin_team_member.destroy

    redirect_to :back
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ProjectResourceController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_admin_project!, except: [:index, :show]

  def index
  end

  def show
    @team_member = project.users_projects.find(params[:id])
    @events = @team_member.user.recent_events.where(:project_id => @project.id).limit(7)
  end

  def new
    @team_member = project.users_projects.new
  end

  def create
    @project.add_users_ids_to_team(
      params[:user_ids],
      params[:project_access]
    )

    redirect_to project_team_index_path(@project)
  end

  def update
    @team_member = project.users_projects.find(params[:id])
    @team_member.update_attributes(params[:team_member])

    unless @team_member.valid?
      flash[:alert] = "User should have at least one role"
    end
    redirect_to project_team_index_path(@project)
  end

  def destroy
    @team_member = project.users_projects.find(params[:id])
    @team_member.destroy

    respond_to do |format|
      format.html { redirect_to project_team_index_path(@project) }
      format.js { render nothing: true }
    end
  end
end

app/views/team_members/_form.html.haml
%h3.page_title
  = "New Team member(s)"
%hr
= form_for @team_member, as: :team_member, url: project_team_members_path(@project, @team_member) do |f|
  -if @team_member.errors.any?
    .alert-message.block-message.error
      %ul
        - @team_member.errors.full_messages.each do |msg|
          %li= msg

  %h6 1. Choose people you want in the team
  .clearfix
    = f.label :user_ids, "People"
    .input= select_tag(:user_ids, options_from_collection_for_select(User.not_in_project(@project).all, :id, :name), {data: {placeholder: "Select users"}, class: "chosen xxlarge", multiple: true})

  %h6 2. Set access level for them
  .clearfix
    = f.label :project_access, "Project Access"
    .input= select_tag :project_access, options_for_select(Project.access_options, @team_member.project_access), class: "project-access-select chosen"

  .actions
    = f.submit 'Save', class: "btn save-btn"
    = link_to "Cancel", project_team_index_path(@project), class: "btn cancel-btn"

app/views/team_members/_show.html.haml
- user = member.user
- allow_admin = can? current_user, :admin_project, @project
%tr{id: dom_id(member), class: "team_member_row user_#{user.id}"}
  %td.span6
    = link_to project_team_member_path(@project, member), title: user.name, class: "dark" do
      = image_tag gravatar_icon(user.email, 40), class: "avatar s32"
    = link_to project_team_member_path(@project, member), title: user.name, class: "dark" do
      %strong= truncate(user.name, lenght: 40)
      %br
      %small.cgray= user.email

  %td.span5
    .right
      - if current_user == user
        %span.btn.disabled This is you!
      - if @project.owner == user
        %span.btn.disabled.success Owner
      - elsif user.blocked
        %span.btn.disabled.blocked Blocked
      - elsif allow_admin
        = link_to project_team_member_path(project_id: @project, id: member.id), confirm: remove_from_team_message(@project, member), method: :delete, class: "very_small btn danger" do
          %i.icon-minus.icon-white

    - if allow_admin
      = form_for(member, as: :team_member, url: project_team_member_path(@project, member)) do |f|
        = f.select :project_access, options_for_select(UsersProject.access_roles, member.project_access), {}, class: "medium project-access-select span2"

app/views/team_members/_team.html.haml
- grouper_project_members(@project).each do |access, members|
  %table
    %thead
      %tr
        %th.span7
          = Project.access_options.key(access).pluralize
        %th
    %tbody
      - members.each do |up|
        = render(partial: 'team_members/show', locals: {member: up})


:javascript
  $(function(){
    $('.repo-access-select, .project-access-select').live("change", function() {
      $(this.form).submit();
    });
  })

app/views/team_members/create.js.haml
- if @team_member.valid?
  :plain
    $("#new_team_member").hide("slide", { direction: "right" }, 150, function(){
      $("#team-table").show("slide", { direction: "left" }, 150, function() {
        $("#new_team_member").remove();
        $("#team-table").replaceWith("#{escape_javascript(render('projects/team'))}");
        $(".add_new").show();
      });
    });
- else
  :plain
    $("#new_team_member").replaceWith("#{escape_javascript(render('form'))}");
    $('select#team_member_user_id').chosen();

app/views/team_members/index.html.haml
= render "projects/project_head"
%h3.page_title
  Team Members
  %small (#{@project.users_projects.count})

- if can? current_user, :admin_team_member, @project
  %p.slead
    = link_to new_project_team_member_path(@project), class: "btn small right", title: "New Team Member" do
      New Team Member
    Read more about project permissions
    %strong= link_to "here", help_permissions_path, class: "vlink"

= render partial: "team_members/team", locals: {project: @project}

app/views/team_members/new.html.haml
= render "projects/project_head"
= render "team_members/form"

app/views/team_members/show.html.haml
- allow_admin = can? current_user, :admin_project, @project
- user = @team_member.user

.team_member_show
  - if can? current_user, :admin_project, @project
    = link_to 'Remove from team', project_team_member_path(project_id: @project, id: @team_member.id), confirm: 'Are you sure?', method: :delete, class: "right btn danger"
  .profile_avatar_holder
    = image_tag gravatar_icon(user.email, 60), class: "borders"
  %h3
    = user.name
    %small
      = user.email

  %hr
  .back_link
    %br
    = link_to project_team_index_path(@project), class: "" do
      &larr; To team list
  %br
  .row
    .span6
      %table.lite
        %tr
          %td Email
          %td= mail_to user.email
        %tr
          %td Skype
          %td= user.skype
        - unless user.linkedin.blank?
          %tr
            %td LinkedIn
            %td= user.linkedin
        - unless user.twitter.blank?
          %tr
            %td Twitter
            %td= user.twitter
        - unless user.bio.blank?
          %tr
            %td Bio
            %td= user.bio
    .span6
      %table.lite
        %tr
          %td Member since
          %td= @team_member.created_at.stamp("Aug 21, 2011")
        %tr
          %td
            Project Access:
            %small (#{link_to "read more", help_permissions_path, class: "vlink"})
          %td
            = form_for(@team_member, as: :team_member, url: project_team_member_path(@project, @team_member)) do |f|
              = f.select :project_access, options_for_select(Project.access_options, @team_member.project_access), {}, class: "project-access-select", disabled: !allow_admin
  %hr
  = render @events
:javascript
  $(function(){
    $('.repo-access-select, .project-access-select').live("change", function() {
      $(this.form).submit();
    });
  })

app/views/team_members/update.js.haml
- if @team_member.valid?
  :plain
    $("##{dom_id(@team_member)}").effect("highlight", {color: "#529214"}, 1000);;
- else
  :plain
    $("##{dom_id(@team_member)}").effect("highlight", {color: "#D12F19"}, 1000);;