config/routes.rb
Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server => '/info/resque', as: 'resque'

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git_bin_path,
    project_root: Gitlab.config.git_base_path,
    upload_pack:  Gitlab.config.git_upload_pack,
    receive_pack: Gitlab.config.git_receive_pack
  }), at: '/:path', constraints: { path: /[\w-]+\.git/ }

  #
  # Help
  #
  get 'help'              => 'help#index'
  get 'help/permissions'  => 'help#permissions'
  get 'help/workflow'     => 'help#workflow'
  get 'help/api'          => 'help#api'
  get 'help/web_hooks'    => 'help#web_hooks'
  get 'help/system_hooks' => 'help#system_hooks'
  get 'help/markdown'     => 'help#markdown'
  get 'help/ssh'          => 'help#ssh'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, constraints: { id: /[^\/]+/ } do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, only: [:edit, :update, :destroy]
    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end
    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  get "profile/account"             => "profile#account"
  get "profile/history"             => "profile#history"
  put "profile/password"            => "profile#password_update"
  get "profile/token"               => "profile#token"
  put "profile/reset_private_token" => "profile#reset_private_token"
  get "profile"                     => "profile#show"
  get "profile/design"              => "profile#design"
  put "profile/update"              => "profile#update"

  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard"                => "dashboard#index"
  get "dashboard/issues"         => "dashboard#issues"
  get "dashboard/merge_requests" => "dashboard#merge_requests"

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[^\/]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [], path: "/" do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :raw
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /.+/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/}
    match "/compare/:from...:to" => "compare#show", as: "compare", constraints: {from: /.+/, to: /.+/}

    resources :team, controller: 'team_members', only: [:index]
    resources :team_members
    resources :milestones
    resources :labels, only: [:index]
    resources :issues do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#index"
end

app/models/project.rb
require "grit"

class Project < ActiveRecord::Base
  include Repository
  include PushObserver
  include Authority
  include Team

  attr_accessible :name, :path, :description, :code, :default_branch, :issues_enabled,
                  :wall_enabled, :merge_requests_enabled, :wiki_enabled
  attr_accessor :error_code

  # Relations
  belongs_to :owner, class_name: "User"
  has_many :users,          through: :users_projects
  has_many :events,         dependent: :destroy
  has_many :merge_requests, dependent: :destroy
  has_many :issues,         dependent: :destroy, order: "closed, created_at DESC"
  has_many :milestones,     dependent: :destroy
  has_many :users_projects, dependent: :destroy
  has_many :notes,          dependent: :destroy
  has_many :snippets,       dependent: :destroy
  has_many :deploy_keys,    dependent: :destroy, foreign_key: "project_id", class_name: "Key"
  has_many :hooks,          dependent: :destroy, class_name: "ProjectHook"
  has_many :wikis,          dependent: :destroy
  has_many :protected_branches, dependent: :destroy

  # Scopes
  scope :public_only, where(private_flag: false)
  scope :without_user, lambda { |user|  where("id not in (:ids)", ids: user.projects.map(&:id) ) }

  def self.active
    joins(:issues, :notes, :merge_requests).order("issues.created_at, notes.created_at, merge_requests.created_at DESC")
  end

  def self.search query
    where("name like :query or code like :query or path like :query", query: "%#{query}%")
  end

  def self.create_by_user(params, user)
    project = Project.new params

    Project.transaction do
      project.owner = user
      project.save!

      # Add user as project master
      project.users_projects.create!(project_access: UsersProject::MASTER, user: user)

      # when project saved no team member exist so
      # project repository should be updated after first user add
      project.update_repository
    end

    project
  rescue Gitlab::Gitolite::AccessDenied => ex
    project.error_code = :gitolite
    project
  rescue => ex
    project.error_code = :db
    project.errors.add(:base, "Can't save project. Please try again later")
    project
  end

  def git_error?
    error_code == :gitolite
  end

  def saved?
    id && valid?
  end

  # Validations
  validates :owner, presence: true
  validates :description, length: { within: 0..2000 }
  validates :name, uniqueness: true, presence: true, length: { within: 0..255 }
  validates :path, uniqueness: true, presence: true, length: { within: 0..255 },
            format: { with: /\A[a-zA-Z][a-zA-Z0-9_\-\.]*\z/,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }
  validates :code, presence: true, uniqueness: true, length: { within: 1..255 },
            format: { with: /\A[a-zA-Z][a-zA-Z0-9_\-\.]*\z/,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }
  validates :issues_enabled, :wall_enabled, :merge_requests_enabled,
            :wiki_enabled, inclusion: { in: [true, false] }
  validate :check_limit, :repo_name

  def check_limit
    unless owner.can_create_project?
      errors[:base] << ("Your own projects limit is #{owner.projects_limit}! Please contact administrator to increase it")
    end
  rescue
    errors[:base] << ("Can't check your ability to create project")
  end

  def repo_name
    if path == "gitolite-admin"
      errors.add(:path, " like 'gitolite-admin' is not allowed")
    end
  end

  def self.access_options
    UsersProject.access_roles
  end

  def to_param
    code
  end

  def web_url
    [Gitlab.config.url, code].join("/")
  end

  def common_notes
    notes.where(noteable_type: ["", nil]).inc_author_project
  end

  def build_commit_note(commit)
    notes.new(noteable_id: commit.id, noteable_type: "Commit")
  end

  def commit_notes(commit)
    notes.where(noteable_id: commit.id, noteable_type: "Commit", line_code: nil)
  end

  def commit_line_notes(commit)
    notes.where(noteable_id: commit.id, noteable_type: "Commit").where("line_code is not null")
  end

  def public?
    !private_flag
  end

  def private?
    private_flag
  end

  def last_activity
    events.order("created_at ASC").last
  end

  def last_activity_date
    if events.last
      events.last.created_at
    else
      updated_at
    end
  end

  def wiki_notes
    Note.where(noteable_id: wikis.pluck(:id), noteable_type: 'Wiki', project_id: self.id)
  end

  def project_id
    self.id
  end
end

# == Schema Information
#
# Table name: projects
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  path                   :string(255)
#  description            :text
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  private_flag           :boolean         default(TRUE), not null
#  code                   :string(255)
#  owner_id               :integer
#  default_branch         :string(255)
#  issues_enabled         :boolean         default(TRUE), not null
#  wall_enabled           :boolean         default(TRUE), not null
#  merge_requests_enabled :boolean         default(TRUE), not null
#  wiki_enabled           :boolean         default(TRUE), not null
#

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_filter :admin_project, only: [:edit, :show, :update, :destroy, :team_update]

  def index
    @admin_projects = Project.scoped
    @admin_projects = @admin_projects.search(params[:name]) if params[:name].present?
    @admin_projects = @admin_projects.page(params[:page]).per(20)
  end

  def show
    @users = User.scoped
    @users = @users.not_in_project(@admin_project) if @admin_project.users.present?
    @users = @users.all
  end

  def new
    @admin_project = Project.new
  end

  def edit
  end

  def team_update
    @admin_project.add_users_ids_to_team(params[:user_ids], params[:project_access])

    redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
  end

  def create
    @admin_project = Project.new(params[:project])
    @admin_project.owner = current_user

    if @admin_project.save
      redirect_to [:admin, @admin_project], notice: 'Project was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    owner_id = params[:project].delete(:owner_id)

    if owner_id
      @admin_project.owner = User.find(owner_id)
    end

    if @admin_project.update_attributes(params[:project])
      redirect_to [:admin, @admin_project], notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @admin_project.destroy

    redirect_to admin_projects_url, notice: 'Project was successfully deleted.'
  end

  private

  def admin_project
    @admin_project = Project.find_by_code(params[:id])
  end
end

app/controllers/projects_controller.rb
require Rails.root.join('lib', 'gitlab', 'graph_commit')

class ProjectsController < ProjectResourceController
  skip_before_filter :project, only: [:new, :create]

  # Authorize
  before_filter :authorize_read_project!, except: [:index, :new, :create]
  before_filter :authorize_admin_project!, only: [:edit, :update, :destroy]
  before_filter :require_non_empty_project, only: [:blob, :tree, :graph]

  layout 'application', only: [:new, :create]

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.create_by_user(params[:project], current_user)

    respond_to do |format|
      format.html do
        if @project.saved?
          redirect_to(@project, notice: 'Project was successfully created.')
        else
          render action: "new"
        end
      end
      format.js
    end
  end

  def update
    respond_to do |format|
      if project.update_attributes(params[:project])
        format.html { redirect_to edit_project_path(project), notice: 'Project was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def show
    limit = (params[:limit] || 20).to_i
    @events = @project.events.recent.limit(limit).offset(params[:offset] || 0)

    respond_to do |format|
      format.html do
         unless @project.empty_repo?
           @last_push = current_user.recent_push(@project.id)
           render :show
         else
           render "projects/empty"
         end
      end
      format.js
    end
  end

  def files
    @notes = @project.notes.where("attachment != 'NULL'").order("created_at DESC").limit(100)
  end

  #
  # Wall
  #

  def wall
    return render_404 unless @project.wall_enabled
    @note = Note.new

    respond_to do |format|
      format.html
    end
  end

  def graph
    @days_json, @commits_json = Gitlab::GraphCommit.to_graph(project)
  end

  def destroy
    # Disable the UsersProject update_repository call, otherwise it will be
    # called once for every person removed from the project
    UsersProject.skip_callback(:destroy, :after, :update_repository)
    project.destroy
    UsersProject.set_callback(:destroy, :after, :update_repository)

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def grouper_project_members(project)
    @project.users_projects.sort_by(&:project_access).reverse.group_by(&:project_access)
  end

  def remove_from_team_message(project, member)
    "You are going to remove #{member.user_name} from #{project.name}. Are you sure?"
  end

  def link_to_project project
    link_to project.name, project
  end
end

app/views/admin/projects/_form.html.haml
= form_for [:admin, project] do |f|
  -if project.errors.any?
    .alert-message.block-message.error
      %ul
        - project.errors.full_messages.each do |msg|
          %li= msg

  .clearfix.project_name_holder
    = f.label :name do
      Project name is
    .input
      = f.text_field :name, placeholder: "Example Project", class: "xxlarge"

  %hr
  .adv_settings
    %h6 Advanced settings:
    .clearfix
      = f.label :path do
        Path
      .input
        .input-prepend
          %strong
            = text_field_tag :ppath, @admin_project.path_to_repo, class: "xlarge", disabled: true
    .clearfix
      = f.label :code do
        URL
      .input
        .input-prepend
          %span.add-on= web_app_url
          = f.text_field :code, placeholder: "example"

    - unless project.new_record?
      .clearfix
        = f.label :owner_id
        .input= f.select :owner_id, User.all.map { |user| [user.name, user.id] }, {}, {class: 'chosen'}

      - if project.repo_exists?
        .clearfix
          = f.label :default_branch, "Default Branch"
          .input= f.select(:default_branch, project.heads.map(&:name), {}, style: "width:210px;")

  - unless project.new_record?
    %hr
    .adv_settings
      %h6 Features:

      .clearfix
        = f.label :issues_enabled, "Issues"
        .input= f.check_box :issues_enabled

      .clearfix
        = f.label :merge_requests_enabled, "Merge Requests"
        .input= f.check_box :merge_requests_enabled

      .clearfix
        = f.label :wall_enabled, "Wall"
        .input= f.check_box :wall_enabled

      .clearfix
        = f.label :wiki_enabled, "Wiki"
        .input= f.check_box :wiki_enabled

  - unless project.new_record?
    .actions
      = f.submit 'Save Project', class: "btn save-btn"
      = link_to 'Cancel', admin_projects_path, class: "btn cancel-btn"



:javascript
  $(function(){
    new Projects();
  })

app/views/admin/projects/_new_form.html.haml
= form_for [:admin, @admin_project] do |f|
  - if @admin_project.errors.any?
    .alert-message.block-message.error
      %span= @admin_project.errors.full_messages.first
  .clearfix.project_name_holder
    = f.label :name do
      Project name is
    .input
      = f.text_field :name, placeholder: "Example Project", class: "xxlarge"
      = f.submit 'Create project', class: "btn primary project-submit"

  %hr
  %div.adv_settings
    %h6 Advanced settings:
    .clearfix
      = f.label :path do
        Git Clone
      .input
        .input-prepend
          %span.add-on= Gitlab.config.ssh_path
          = f.text_field :path, placeholder: "example_project", disabled: !@admin_project.new_record?
          %span.add-on= ".git"
    .clearfix
      = f.label :code do
        URL
      .input
        .input-prepend
          %span.add-on= web_app_url
          = f.text_field :code, placeholder: "example"

app/views/admin/projects/edit.html.haml
%h3.page_title #{@admin_project.name} &rarr; Edit project 
%hr
= render 'form', project: @admin_project

app/views/admin/projects/index.html.haml
%h3.page_title
  Projects
  = link_to 'New Project', new_admin_project_path, class: "btn small right"
%br
= form_tag admin_projects_path, method: :get, class: 'form-inline' do
  = text_field_tag :name, params[:name], class: "xlarge"
  = submit_tag "Search", class: "btn submit primary"

%table
  %thead
    %th Name
    %th Path
    %th Team Members
    %th Post Receive
    %th Last Commit
    %th Edit
    %th.cred Danger Zone!

  - @admin_projects.each do |project|
    %tr
      %td= link_to project.name, [:admin, project]
      %td= project.path
      %td= project.users_projects.count
      %td= check_box_tag :post_receive_file, 1, project.has_post_receive_file?, disabled: true
      %td= last_commit(project)
      %td= link_to 'Edit', edit_admin_project_path(project), id: "edit_#{dom_id(project)}", class: "btn small"
      %td.bgred= link_to 'Destroy', [:admin, project], confirm: "REMOVE #{project.name}? Are you sure?", method: :delete, class: "btn small danger"
= paginate @admin_projects, theme: "admin"

app/views/admin/projects/new.html.haml
.project_new_holder
  %h3.page_title
    New Project
  %hr
  = render 'new_form'
%div.save-project-loader.hide
  %center
    = image_tag "ajax_loader.gif"
    %h3 Creating project &amp; repository. Please wait a few minutes

:javascript
  $(function(){ new Projects(); });

app/views/admin/projects/show.html.haml
%h3.page_title
  Project: #{@admin_project.name}
  = link_to edit_admin_project_path(@admin_project), class: "btn right" do
    %i.icon-edit
    Edit

%br
%table.zebra-striped
  %thead
    %tr
      %th Project
      %th
  %tr
    %td
      %b
        Name:
    %td
      = @admin_project.name
  %tr
    %td
      %b
        Code:
    %td
      = @admin_project.code
  %tr
    %td
      %b
        Path:
    %td
      = @admin_project.path
  %tr
    %td
      %b
        Owner:
    %td
      = @admin_project.owner.name
  %tr
    %td
      %b
        Post Receive File:
    %td
      = check_box_tag :post_receive_file, 1, @admin_project.has_post_receive_file?, disabled: true
%br
%h3
  Team
  %small
    (#{@admin_project.users_projects.count})
%br
%table.zebra-striped
  %thead
    %tr
      %th Name
      %th Project Access
      %th Repository Access
      %th

  - @admin_project.users_projects.each do |tm|
    %tr
      %td
        = link_to tm.user_name, admin_user_path(tm.user)
      %td= tm.project_access_human
      %td= link_to 'Edit Access', edit_admin_team_member_path(tm), class: "btn small"
      %td= link_to 'Remove from team', admin_team_member_path(tm), confirm: 'Are you sure?', method: :delete, class: "btn danger small"

%br
%h3 Add new team member
%br
= form_tag team_update_admin_project_path(@admin_project), class: "bulk_import", method: :put  do
  %table.zebra-striped
    %thead
      %tr
        %th Users
        %th Project Access:

    %tr
      %td= select_tag :user_ids, options_from_collection_for_select(@users , :id, :name), multiple: true, data: {placeholder: 'Select users'}, class: 'chosen span5'
      %td= select_tag :project_access, options_for_select(Project.access_options), {class: "project-access-select chosen span3"}

    %tr
      %td= submit_tag 'Add', class: "btn primary"
      %td
        Read more about project permissions
        %strong= link_to "here", help_permissions_path, class: "vlink"